### FIFA world cup

team_dict = {'2018' : {'teams' : ["URUGUAY", "RUSSIA", "SAUDI ARABIA", "EGYPT",
                                  "SPAIN", "PORTUGAL", "IRAN", "MOROCCO",
                                  "FRANCE", "DENMARK", "PERU", "AUSTRALIA",
                                  "CROATIA", "ARGENTINA", "NIGERIA", "ICELAND",
                                  "BRAZIL", "SWITZERLAND", "SERBIA", "COSTA RICA",
                                  "SWEDEN", "MEXICO", "KOREA", "GERMANY",
                                  "BELGIUM", "ENGLAND", "TUNISIA", "PANAMA",
                                  "COLOMBIA", "JAPAN", "SENEGAL", "POLAND"],
                       'teamsGS':[['RUSSIA','SAUDI ARABIA'],
                                  ['EGYPT','URUGUAY'],
                                  ['MOROCCO','IRAN'],
                                  ['PORTUGAL','SPAIN'],
                                  ['FRANCE','AUSTRALIA'],
                                  ['ARGENTINA','ICELAND'],
                                  ['PERU','DENMARK'],
                                  ['CROATIA','NIGERIA'],
                                  ['COSTA RICA','SERBIA'],
                                  ['GERMANY','MEXICO'],
                                  ['BRAZIL','SWITZERLAND'],
                                  ['SWEDEN','KOREA'],
                                  ['BELGIUM','PANAMA'],
                                  ['TUNISIA','ENGLAND'],
                                  ['COLOMBIA','JAPAN'],
                                  ['POLAND','SENEGAL'],
                                  ['RUSSIA','EGYPT'],
                                  ['PORTUGAL','MOROCCO'],
                                  ['URUGUAY','SAUDI ARABIA'],
                                  ['IRAN','SPAIN'],
                                  ['DENMARK','AUSTRALIA'],
                                  ['FRANCE','PERU'],
                                  ['ARGENTINA','CROATIA'],
                                  ['BRAZIL','COSTA RICA'],
                                  ['NIGERIA','ICELAND'],
                                  ['SERBIA','SWITZERLAND'],
                                  ['BELGIUM','TUNISIA'],
                                  ['KOREA','MEXICO'],
                                  ['GERMANY','SWEDEN'],
                                  ['ENGLAND','PANAMA'],
                                  ['JAPAN','SENEGAL'],
                                  ['POLAND','COLOMBIA'],
                                  ['URUGUAY','RUSSIA'],
                                  ['SAUDI ARABIA','EGYPT'],
                                  ['SPAIN','MOROCCO'],
                                  ['IRAN','PORTUGAL'],
                                  ['AUSTRALIA', 'PERU'],
                                  ['DENMARK', 'FRANCE'],
                                  ['NIGERIA', 'ARGENTINA'],
                                  ['ICELAND', 'CROATIA'],
                                  ['KOREA', 'GERMANY'],
                                  ['MEXICO', 'SWEDEN'],
                                  ['SERBIA', 'BRAZIL'],
                                  ['SWITZERLAND', 'COSTA RICA'],
                                  ['JAPAN', 'POLAND'],
                                  ['SENEGAL', 'COLOMBIA'],
                                  ['PANAMA', 'TUNISIA'],
                                  ['ENGLAND', 'BELGIUM']],
                       'teams16':[['SPAIN','RUSSIA'],
                                  ['CROATIA','DENMARK'],
                                  ['SWEDEN','SWITZERLAND'],
                                  ['COLOMBIA','ENGLAND'],
                                  ['URUGUAY','PORTUGAL'],
                                  ['FRANCE','ARGENTINA'],
                                  ['BRAZIL','MEXICO'],
                                  ['BELGIUM','JAPAN']],
                       'teamsQF':[['RUSSIA','CROATIA'],
                                  ['SWEDEN','ENGLAND'],
                                  ['URUGUAY','FRANCE'],
                                  ['BRAZIL','BELGIUM']],
                       'teamsSF':[['FRANCE','BELGIUM'],
                                  ['CROATIA','ENGLAND']],
                       'teamsFF':[['BELGIUM','ENGLAND'],
                                  ['FRANCE','CROATIA']]},
             '2019' : {'teams' : ["FRANCE", "NORWAY", "NIGERIA", "KOREA",
                                  "GERMANY", "SPAIN", "CHINA", "SOUTH AFRICA",
                                  "ITALY", "AUSTRALIA", "BRAZIL", "JAMAICA",
                                  "ENGLAND", "JAPAN", "ARGENTINA", "SCOTLAND",
                                  "NETHERLANDS", "CANADA", "CAMEROON", "NEW ZEALAND",
                                  "USA", "SWEDEN", "CHILE", "THAILAND"],
                       'teamsGS':[['FRANCE','KOREA'],
                                  ['GERMANY','CHINA'],
                                  ['SPAIN','SOUTH AFRICA'],
                                  ['NORWAY','NIGERIA'],
                                  ['AUSTRALIA','ITALY'],
                                  ['BRAZIL','JAMAICA'],
                                  ['ENGLAND','SCOTLAND'],
                                  ['ARGENTINA','JAPAN'],
                                  ['CANADA','CAMEROON'],
                                  ['NEW ZEALAND','NETHERLANDS'],
                                  ['CHILE','SWEDEN'],
                                  ['USA','THAILAND'],
                                  ['NIGERIA','KOREA'],
                                  ['GERMANY','SPAIN'],
                                  ['FRANCE','NORWAY'],
                                  ['AUSTRALIA','BRAZIL'],
                                  ['SOUTH AFRICA','CHINA'],
                                  ['JAPAN','SCOTLAND'],
                                  ['JAMAICA','ITALY'],
                                  ['ENGLAND','ARGENTINA'],
                                  ['NETHERLANDS','CAMEROON'],
                                  ['CANADA','NEW ZEALAND'],
                                  ['SWEDEN','THAILAND'],
                                  ['USA','CHILE'],
                                  ['CHINA','SPAIN'],
                                  ['SOUTH AFRICA','GERMANY'],
                                  ['NIGERIA','FRANCE'],
                                  ['KOREA','NORWAY'],
                                  ['JAMAICA','AUSTRALIA'],
                                  ['ITALY','BRAZIL'],
                                  ['JAPAN','ENGLAND'],
                                  ['SCOTLAND','ARGENTINA'],
                                  ['CAMEROON','NEW ZEALAND'],
                                  ['NETHERLANDS','CANADA'],
                                  ['SWEDEN','USA'],
                                  ['THAILAND','CHILE']],
                       'teams16':[['GERMANY','NIGERIA'],
                                  ['SWEDEN','CANADA'],
                                  ['ITALY','CHINA'],
                                  ['NETHERLANDS','JAPAN'],
                                  ['NORWAY','AUSTRALIA'],
                                  ['ENGLAND','CAMEROON'],
                                  ['FRANCE','BRAZIL'],
                                  ['SPAIN','USA']],
                       'teamsQF':[['GERMANY','SWEDEN'],
                                  ['ITALY','NETHERLANDS'],
                                  ['NORWAY','ENGLAND'],
                                  ['FRANCE','USA']],
                       'teamsSF':[['ENGLAND','USA'],
                                  ['SWEDEN','NETHERLANDS']],
                       'teamsFF':[['ENGLAND','SWEDEN'],
                                  ['USA','NETHERLANDS']]},
             'CL20' : {'teams' : ["PARI", "REAL", "CLUB", "GALA",
                                  "BAYE", "TOTT", "OLYM", "CRVE",
                                  "MANC", "ATAL", "SHAK", "DINA",
                                  "JUVE", "ATLE", "LEVE", "LOKO",
                                  "LIVE", "NAPO", "SALZ", "GENK",
                                  "BARC", "DORT", "INTE", "SLAV",
                                  "LEIP", "LYON", "BENF", "ZENI",
                                  "VALE", "CHEL", "AJAX", "LOSC"],
                       'teamsGS':[['INTE','SLAV'],
                                  ['LYON','ZENI'],
                                  ['NAPO','LIVE'],
                                  ['SALZ','GENK'],
                                  ['DORT','BARC'],
                                  ['BENF','LEIP'],
                                  ['CHEL','VALE'],
                                  ['AJAX','LOSC'],
                                  ['CLUB','GALA'],
                                  ['OLYM','TOTT'],
                                  ['PARI','REAL'],
                                  ['BAYE','CRVE'],
                                  ['DINA','ATAL'],
                                  ['SHAK','MANC'],
                                  ['LEVE','LOKO'],
                                  ['ATLE','JUVE'],
                                  ['REAL','CLUB'],
                                  ['ATAL','SHAK'],
                                  ['GALA','PARI'],
                                  ['TOTT','BAYE'],
                                  ['CRVE','OLYM'],
                                  ['MANC','DINA'],
                                  ['JUVE','LEVE'],
                                  ['LOKO','ATLE'],
                                  ['GENK','NAPO'],
                                  ['SLAV','DORT'],
                                  ['LIVE','SALZ'],
                                  ['BARC','INTE'],
                                  ['LEIP','LYON'],
                                  ['ZENI','BENF'],
                                  ['LOSC','CHEL'],
                                  ['VALE','AJAX'],
                                  ['SHAK','DINA'],
                                  ['ATLE','LEVE'],
                                  ['CLUB','PARI'],
                                  ['GALA','REAL'],
                                  ['OLYM','BAYE'],
                                  ['TOTT','CRVE'],
                                  ['MANC','ATAL'],
                                  ['JUVE','LOKO'],
                                  ['LEIP','ZENI'],
                                  ['AJAX','CHEL'],
                                  ['SALZ','NAPO'],
                                  ['GENK','LIVE'],
                                  ['INTE','DORT'],
                                  ['SLAV','BARC'],
                                  ['BENF','LYON'],
                                  ['LOSC','VALE'],
                                  ['BARC','SLAV'],
                                  ['ZENI','LEIP'],
                                  ['NAPO','SALZ'],
                                  ['LIVE','GENK'],
                                  ['DORT','INTE'],
                                  ['LYON','BENF'],
                                  ['CHEL','AJAX'],
                                  ['VALE','LOSC'],
                                  ['BAYE','OLYM'],
                                  ['LOKO','JUVE'],
                                  ['PARI','CLUB'],
                                  ['REAL','GALA'],
                                  ['CRVE','TOTT'],
                                  ['DINA','SHAK'],
                                  ['ATAL','MANC'],
                                  ['LEVE','ATLE'],
                                  ['GALA','CLUB'],
                                  ['LOKO','LEVE'],
                                  ['REAL','PARI'],
                                  ['CRVE','BAYE'],
                                  ['TOTT','OLYM'],
                                  ['ATAL','DINA'],
                                  ['MANC','SHAK'],
                                  ['JUVE','ATLE'],
                                  ['ZENI','LYON'],
                                  ['VALE','CHEL'],
                                  ['LIVE','NAPO'],
                                  ['GENK','SALZ'],
                                  ['BARC','DORT'],
                                  ['SLAV','INTE'],
                                  ['LEIP','BENF'],
                                  ['LOSC','AJAX'],
                                  ['NAPO','GENK'],
                                  ['SALZ','LIVE'],
                                  ['DORT','SLAV'],
                                  ['INTE','BARC'],
                                  ['LYON','LEIP'],
                                  ['BENF','ZENI'],
                                  ['CHEL','LOSC'],
                                  ['AJAX','VALE'],
                                  ['DINA','MANC'],
                                  ['SHAK','ATAL'],
                                  ['PARI','GALA'],
                                  ['CLUB','REAL'],
                                  ['BAYE','TOTT'],
                                  ['OLYM','CRVE'],
                                  ['LEVE','JUVE'],
                                  ['ATLE','LOKO']],
                       'teams16':[['ATLE','LIVE'],
                                  ['DORT','PARI'],
                                  ['ATAL','VALE'],
                                  ['TOTT','LEIP'],
                                  ['CHEL','BAYE'],
                                  ['NAPO','BARC'],
                                  ['LYON','JUVE'],
                                  ['REAL','MANC'],
                                  ['VALE','ATAL'],
                                  ['LEIP','TOTT'],
                                  ['LIVE','ATLE'],
                                  ['PARI','DORT'],
                                  ['JUVE','LYON'],
                                  ['MANC','REAL'],
                                  ['BAYE','CHEL'],
                                  ['BARC','NAPO']],
                       'teamsQF':[['ATAL','PARI'],
                                  ['LEIP','ATLE'],
                                  ['BARC','BAYE'],
                                  ['MANC','LYON']],
                       'teamsSF':[['LEIP','PARI'],
                                  ['LYON','BAYE']],
                       'teamsFF':[['PARI','BAYE']]},
            'UEFA2020':{'teams':['TURKEY',
 'ITALY',
 'WALES',
 'SWITZERLAND',
 'DENMARK',
 'FINLAND',
 'BELGIUM',
 'RUSSIA',
 'AUSTRIA',
 'N MACEDONIA',
 'NETHERLANDS',
 'UKRAINE',
 'ENGLAND',
 'CROATIA',
 'SCOTLAND',
 'CZECH REP',
 'POLAND',
 'SLOVAKIA',
 'SPAIN',
 'SWEDEN',
 'HUNGARY',
 'PORTUGAL',
 'FRANCE',
 'GERMANY',
 'TURKEY',
 'WALES',
 'ITALY',
 'SWITZERLAND',
 'FINLAND',
 'RUSSIA',
 'DENMARK',
 'BELGIUM',
 'UKRAINE',
 'N MACEDONIA',
 'NETHERLANDS',
 'AUSTRIA',
 'CROATIA',
 'CZECH REP',
 'ENGLAND',
 'SCOTLAND',
 'SWEDEN',
 'SLOVAKIA',
 'SPAIN',
 'POLAND',
 'HUNGARY',
 'FRANCE',
 'PORTUGAL',
 'GERMANY',
 'ITALY',
 'WALES',
 'SWITZERLAND',
 'TURKEY',
 'FINLAND',
 'BELGIUM',
 'RUSSIA',
 'DENMARK',
 'UKRAINE',
 'AUSTRIA',
 'N MACEDONIA',
 'NETHERLANDS',
 'CZECH REP',
 'ENGLAND',
 'CROATIA',
 'SCOTLAND',
 'SWEDEN',
 'POLAND',
 'SLOVAKIA',
 'SPAIN',
 'GERMANY',
 'HUNGARY',
 'PORTUGAL',
 'FRANCE',
 'BELGIUM',
 'PORTUGAL',
 'ITALY',
 'AUSTRIA',
 'FRANCE',
 'SWITZERLAND',
 'CROATIA',
 'SPAIN',
 'SWEDEN',
 'UKRAINE',
 'ENGLAND',
 'GERMANY',
 'NETHERLANDS',
 'CZECH REP',
 'WALES',
 'DENMARK',
 'BELGIUM',
 'ITALY',
 'SWITZERLAND',
 'SPAIN',
 'UKRAINE',
 'ENGLAND',
 'CZECH REP',
 'DENMARK',
 'ITALY',
 'SPAIN',
 'ENGLAND',
 'DENMARK'],
 'teamsGS':[['TURKEY', 'ITALY'],
 ['WALES', 'SWITZERLAND'],
 ['DENMARK', 'FINLAND'],
 ['BELGIUM', 'RUSSIA'],
 ['AUSTRIA', 'N MACEDONIA'],
 ['NETHERLANDS', 'UKRAINE'],
 ['ENGLAND', 'CROATIA'],
 ['SCOTLAND', 'CZECH REP'],
 ['POLAND', 'SLOVAKIA'],
 ['SPAIN', 'SWEDEN'],
 ['HUNGARY', 'PORTUGAL'],
 ['FRANCE', 'GERMANY'],
 ['TURKEY', 'WALES'],
 ['ITALY', 'SWITZERLAND'],
 ['FINLAND', 'RUSSIA'],
 ['DENMARK', 'BELGIUM'],
 ['UKRAINE', 'N MACEDONIA'],
 ['NETHERLANDS', 'AUSTRIA'],
 ['CROATIA', 'CZECH REP'],
 ['ENGLAND', 'SCOTLAND'],
 ['SWEDEN', 'SLOVAKIA'],
 ['SPAIN', 'POLAND'],
 ['HUNGARY', 'FRANCE'],
 ['PORTUGAL', 'GERMANY'],
 ['ITALY', 'WALES'],
 ['SWITZERLAND', 'TURKEY'],
 ['FINLAND', 'BELGIUM'],
 ['RUSSIA', 'DENMARK'],
 ['UKRAINE', 'AUSTRIA'],
 ['N MACEDONIA', 'NETHERLANDS'],
 ['CZECH REP', 'ENGLAND'],
 ['CROATIA', 'SCOTLAND'],
 ['SWEDEN', 'POLAND'],
 ['SLOVAKIA', 'SPAIN'],
 ['GERMANY', 'HUNGARY'],
 ['PORTUGAL', 'FRANCE']],
 'teams16':[['BELGIUM', 'PORTUGAL'],
 ['ITALY', 'AUSTRIA'],
 ['FRANCE', 'SWITZERLAND'],
 ['CROATIA', 'SPAIN'],
 ['SWEDEN', 'UKRAINE'],
 ['ENGLAND', 'GERMANY'],
 ['NETHERLANDS', 'CZECH REP'],
 ['WALES', 'DENMARK']],
 'teamsQF':[['BELGIUM', 'ITALY'],
 ['SWITZERLAND', 'SPAIN'],
 ['UKRAINE', 'ENGLAND'],
 ['CZECH REP', 'DENMARK']],
 'teamsSF':[['ITALY', 'SPAIN'], ['ENGLAND', 'DENMARK']],
 'teamsFF':[['ITALY', 'ENGLAND']]
            }
}

### END ###
