### FIFA world cup

team_dict = {'2018' : {'teams' : ["URUGUAY", "RUSSIA", "SAUDI ARABIA", "EGYPT",
                                  "SPAIN", "PORTUGAL", "IRAN", "MOROCCO",
                                  "FRANCE", "DENMARK", "PERU", "AUSTRALIA",
                                  "CROATIA", "ARGENTINA", "NIGERIA", "ICELAND",
                                  "BRAZIL", "SWITZERLAND", "SERBIA", "COSTA RICA",
                                  "SWEDEN", "MEXICO", "KOREA", "GERMANY",
                                  "BELGIUM", "ENGLAND", "TUNISIA", "PANAMA",
                                  "COLOMBIA", "JAPAN", "SENEGAL", "POLAND"],
                       'teamsGS':[['RUSSIA','SAUDI ARABIA'],
                                  ['EGYPT','URUGUAY'],
                                  ['MOROCCO','IRAN'],
                                  ['PORTUGAL','SPAIN'],
                                  ['FRANCE','AUSTRALIA'],
                                  ['ARGENTINA','ICELAND'],
                                  ['PERU','DENMARK'],
                                  ['CROATIA','NIGERIA'],
                                  ['COSTA RICA','SERBIA'],
                                  ['GERMANY','MEXICO'],
                                  ['BRAZIL','SWITZERLAND'],
                                  ['SWEDEN','KOREA'],
                                  ['BELGIUM','PANAMA'],
                                  ['TUNISIA','ENGLAND'],
                                  ['COLOMBIA','JAPAN'],
                                  ['POLAND','SENEGAL'],
                                  ['RUSSIA','EGYPT'],
                                  ['PORTUGAL','MOROCCO'],
                                  ['URUGUAY','SAUDI ARABIA'],
                                  ['IRAN','SPAIN'],
                                  ['DENMARK','AUSTRALIA'],
                                  ['FRANCE','PERU'],
                                  ['ARGENTINA','CROATIA'],
                                  ['BRAZIL','COSTA RICA'],
                                  ['NIGERIA','ICELAND'],
                                  ['SERBIA','SWITZERLAND'],
                                  ['BELGIUM','TUNISIA'],
                                  ['KOREA','MEXICO'],
                                  ['GERMANY','SWEDEN'],
                                  ['ENGLAND','PANAMA'],
                                  ['JAPAN','SENEGAL'],
                                  ['POLAND','COLOMBIA'],
                                  ['URUGUAY','RUSSIA'],
                                  ['SAUDI ARABIA','EGYPT'],
                                  ['SPAIN','MOROCCO'],
                                  ['IRAN','PORTUGAL'],
                                  ['AUSTRALIA', 'PERU'],
                                  ['DENMARK', 'FRANCE'],
                                  ['NIGERIA', 'ARGENTINA'],
                                  ['ICELAND', 'CROATIA'],
                                  ['KOREA', 'GERMANY'],
                                  ['MEXICO', 'SWEDEN'],
                                  ['SERBIA', 'BRAZIL'],
                                  ['SWITZERLAND', 'COSTA RICA'],
                                  ['JAPAN', 'POLAND'],
                                  ['SENEGAL', 'COLOMBIA'],
                                  ['PANAMA', 'TUNISIA'],
                                  ['ENGLAND', 'BELGIUM']],
                       'teams16':[['SPAIN','RUSSIA'],
                                  ['CROATIA','DENMARK'],
                                  ['SWEDEN','SWITZERLAND'],
                                  ['COLOMBIA','ENGLAND'],
                                  ['URUGUAY','PORTUGAL'],
                                  ['FRANCE','ARGENTINA'],
                                  ['BRAZIL','MEXICO'],
                                  ['BELGIUM','JAPAN']],
                       'teamsQF':[['RUSSIA','CROATIA'],
                                  ['SWEDEN','ENGLAND'],
                                  ['URUGUAY','FRANCE'],
                                  ['BRAZIL','BELGIUM']],
                       'teamsSF':[['FRANCE','BELGIUM'],
                                  ['CROATIA','ENGLAND']],
                       'teamsFF':[['BELGIUM','ENGLAND'],
                                  ['FRANCE','CROATIA']]},
             '2019' : {'teams' : ["FRANCE", "NORWAY", "NIGERIA", "KOREA",
                                  "GERMANY", "SPAIN", "CHINA", "SOUTH AFRICA",
                                  "ITALY", "AUSTRALIA", "BRAZIL", "JAMAICA",
                                  "ENGLAND", "JAPAN", "ARGENTINA", "SCOTLAND",
                                  "NETHERLANDS", "CANADA", "CAMEROON", "NEW ZEALAND",
                                  "USA", "SWEDEN", "CHILE", "THAILAND"],
                       'teamsGS':[['FRANCE','KOREA'],
                                  ['GERMANY','CHINA'],
                                  ['SPAIN','SOUTH AFRICA'],
                                  ['NORWAY','NIGERIA'],
                                  ['AUSTRALIA','ITALY'],
                                  ['BRAZIL','JAMAICA'],
                                  ['ENGLAND','SCOTLAND'],
                                  ['ARGENTINA','JAPAN'],
                                  ['CANADA','CAMEROON'],
                                  ['NEW ZEALAND','NETHERLANDS'],
                                  ['CHILE','SWEDEN'],
                                  ['USA','THAILAND'],
                                  ['NIGERIA','KOREA'],
                                  ['GERMANY','SPAIN'],
                                  ['FRANCE','NORWAY'],
                                  ['AUSTRALIA','BRAZIL'],
                                  ['SOUTH AFRICA','CHINA'],
                                  ['JAPAN','SCOTLAND'],
                                  ['JAMAICA','ITALY'],
                                  ['ENGLAND','ARGENTINA'],
                                  ['NETHERLANDS','CAMEROON'],
                                  ['CANADA','NEW ZEALAND'],
                                  ['SWEDEN','THAILAND'],
                                  ['USA','CHILE'],
                                  ['CHINA','SPAIN'],
                                  ['SOUTH AFRICA','GERMANY'],
                                  ['NIGERIA','FRANCE'],
                                  ['KOREA','NORWAY'],
                                  ['JAMAICA','AUSTRALIA'],
                                  ['ITALY','BRAZIL'],
                                  ['JAPAN','ENGLAND'],
                                  ['SCOTLAND','ARGENTINA'],
                                  ['CAMEROON','NEW ZEALAND'],
                                  ['NETHERLANDS','CANADA'],
                                  ['SWEDEN','USA'],
                                  ['THAILAND','CHILE']],
                       'teams16':[['GERMANY','NIGERIA'],
                                  ['SWEDEN','CANADA'],
                                  ['ITALY','CHINA'],
                                  ['NETHERLANDS','JAPAN'],
                                  ['NORWAY','AUSTRALIA'],
                                  ['ENGLAND','CAMEROON'],
                                  ['FRANCE','BRAZIL'],
                                  ['SPAIN','USA']],
                       'teamsQF':[['GERMANY','SWEDEN'],
                                  ['ITALY','NETHERLANDS'],
                                  ['NORWAY','ENGLAND'],
                                  ['FRANCE','USA']],
                       'teamsSF':[['ENGLAND','USA'],
                                  ['SWEDEN','NETHERLANDS']],
                       'teamsFF':[['ENGLAND','SWEDEN'],
                                  ['USA','NETHERLANDS']]}
}

### END ###
