### FIFA women's world cup 2019

teams = ["URUGUAY", "RUSSIA", "SAUDI ARABIA", "EGYPT",
         "SPAIN", "PORTUGAL", "IRAN", "MOROCCO",
         "FRANCE", "DENMARK", "PERU", "AUSTRALIA",
         "CROATIA", "ARGENTINA", "NIGERIA", "ICELAND",
         "BRAZIL", "SWITZERLAND", "SERBIA", "COSTA RICA",
         "SWEDEN", "MEXICO", "KOREA", "GERMANY",
         "BELGIUM", "ENGLAND", "TUNISIA", "PANAMA",
         "COLOMBIA", "JAPAN", "SENEGAL", "POLAND"]

teamsGS = [['RUSSIA','SAUDI ARABIA'],
           ['EGYPT','URUGUAY'],
           ['MOROCCO','IRAN'],
           ['PORTUGAL','SPAIN'],
           ['FRANCE','AUSTRALIA'],
           ['ARGENTINA','ICELAND'],
           ['PERU','DENMARK'],
           ['CROATIA','NIGERIA'],
           ['COSTA RICA','SERBIA'],
           ['GERMANY','MEXICO'],
           ['BRAZIL','SWITZERLAND'],
           ['SWEDEN','KOREA'],
           ['BELGIUM','PANAMA'],
           ['TUNISIA','ENGLAND'],
           ['COLOMBIA','JAPAN'],
           ['POLAND','SENEGAL'],
           ['RUSSIA','EGYPT'],
           ['PORTUGAL','MOROCCO'],
           ['URUGUAY','SAUDI ARABIA'],
           ['IRAN','SPAIN'],
           ['DENMARK','AUSTRALIA'],
           ['FRANCE','PERU'],
           ['ARGENTINA','CROATIA'],
           ['BRAZIL','COSTA RICA'],
           ['NIGERIA','ICELAND'],
           ['SERBIA','SWITZERLAND'],
           ['BELGIUM','TUNISIA'],
           ['KOREA','MEXICO'],
           ['GERMANY','SWEDEN'],
           ['ENGLAND','PANAMA'],
           ['JAPAN','SENEGAL'],
           ['POLAND','COLOMBIA'],
           ['URUGUAY','RUSSIA'],
           ['SAUDI ARABIA','EGYPT'],
           ['SPAIN','MOROCCO'],
           ['IRAN','PORTUGAL'],
           ['AUSTRALIA', 'PERU'],
           ['DENMARK', 'FRANCE'],
           ['NIGERIA', 'ARGENTINA'],
           ['ICELAND', 'CROATIA'],
           ['KOREA', 'GERMANY'],
           ['MEXICO', 'SWEDEN'],
           ['SERBIA', 'BRAZIL'],
           ['SWITZERLAND', 'COSTA RICA'],
           ['JAPAN', 'POLAND'],
           ['SENEGAL', 'COLOMBIA'],
           ['PANAMA', 'TUNISIA'],
           ['ENGLAND', 'BELGIUM']]

teams16 = [['SPAIN','RUSSIA'],
           ['CROATIA','DENMARK'],
           ['SWEDEN','SWITZERLAND'],
           ['COLOMBIA','ENGLAND'],
           ['URUGUAY','PORTUGAL'],
           ['FRANCE','ARGENTINA'],
           ['BRAZIL','MEXICO'],
           ['BELGIUM','JAPAN']]

teamsQF = [['RUSSIA','CROATIA'],
           ['SWEDEN','ENGLAND'],
           ['URUGUAY','FRANCE'],
           ['BRAZIL','BELGIUM']]

teamsSF = [['FRANCE','BELGIUM'],
           ['CROATIA','ENGLAND']]

teamsFF = [['BELGIUM','ENGLAND'],
           ['FRANCE','CROATIA']]
        
### END ###
